server:
  port: 3001

spring:
  application:
    name:  springcloud-config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:doubleWing1016/springcloud-config.git
          skipSslValidation: true