server:
  port: 9000

spring:
  application:
    name: springcloud-zuul

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka,http://eureka7003:7003/eureka
  instance:
    instance-id: zuul-9000
    prefer-ip-address: true


zuul:
  ignored-services: "*"
  routes:
    mydept.serviceId: springcloud-dept
    mydept.path: /dhp/**


info:
  app.name: springcloud
  company.name: dhp
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}