server:
  port: 7003

eureka:
  instance:
    hostname: eureka7003
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/