server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7003:7003/eureka/,http://eureka7002:7002/eureka/
